# This workflow posts an automated comment on every new issue
# https://github.com/marketplace/actions/create-or-update-comment (https://github.com/peter-evans/create-or-update-comment)

name: Automatic Comment
on:
  issues:
    types: [opened]
permissions:
  contents: read

jobs:
  comment:
    permissions:
      issues: write # create or update comment
      pull-requests: write # create or update comment
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Automatic Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for the issue, our team will look into it as soon as possible! If you would like to work on this issue, please wait for a maintainer to decide if it is ready to be worked on.

            To claim an issue, please leave a comment that says ".take". If you have any questions, feel free to ping a maintainer.

          # For full info on how to contribute, please check out our [contributors guide]().
