# This workflow automatically publishes to npm when a release-PR is merged
name: Build and release

on:
  push:
    branches:
      - main


permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: ${github.ref_name}}
          token: ${{secrets.GH_PAT}}
          if: ${{ steps.release.outputs.release_created }}
      # The logic below handles the npm publication:
      - name: Publish to NPM
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm install
          npm test
          npm run code:publish
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
        if: ${{ steps.release.outputs.release_created }}
        
