name: Wiki update and sync

on:
  push:
    branches:
      - main
    paths:
      - '.github/wiki/**'
  repository_dispatch:
    types: [docs]
  gollum:

permissions:
  contents: write

env:
  GIT_AUTHOR_NAME: Wikibot

jobs:
  sync-docs-to-wiki:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          source: ./github/wiki
          destination: wiki
          token: ${{secrets.GH_PAT}}
          gitAuthorName: ${{env.GIT_AUTHOR_NAME}}

  sync-wiki-to-docs:
    runs-on: ubuntu-latest
    if: github.event_name == 'gollum'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GH_PAT}}
          ref: main
      - name: Sync wiki to docs
        uses: newrelic/wiki-sync-action@main
        with:
          source: wiki
          destination: ./github/wiki
          token: ${{secrets.GH_PAT}}
          gitAuthorName: ${{env.GIT_AUTHOR_NAME}}
          branch: main
